# Generated by Django 2.1.2 on 2018-12-12 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Licence', models.AutoField(primary_key=True, serialize=False, verbose_name='Licence Student')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('Name1', models.CharField(max_length=50, verbose_name='Name')),
                ('Name2', models.CharField(blank=True, max_length=50, null=True)),
                ('Name3', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName1', models.CharField(blank=True, max_length=50)),
                ('LastName2', models.CharField(blank=True, max_length=50, null=True)),
                ('BirthDate', models.DateField(null=True, verbose_name='Birth Name')),
                ('Email', models.EmailField(max_length=80, null=True)),
                ('Phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='Contact Phone')),
                ('DPI', models.IntegerField(verbose_name='DPI')),
                ('Photo', models.ImageField(upload_to='photos/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('IdAssistance', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='AssistanceList',
            fields=[
                ('IdAssistanceList', models.AutoField(primary_key=True, serialize=False)),
                ('Estate', models.BooleanField(default=False, verbose_name='1 Assistence; 0 No Assistence')),
                ('FKIdAssistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Assistance')),
                ('FKLicence', models.ForeignKey(limit_choices_to={'FKLicenceType': 8}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('IdCourse', models.AutoField(primary_key=True, serialize=False)),
                ('NameCourse', models.CharField(max_length=45)),
                ('Description', models.TextField()),
                ('Teacher', models.ForeignKey(blank=True, limit_choices_to={'FKLicenceType': 7}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListStudents',
            fields=[
                ('IdListStudents', models.AutoField(primary_key=True, serialize=False)),
                ('FKIdCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course')),
                ('FKLicence', models.ForeignKey(limit_choices_to={'FKLicenceType': 8}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('LicenceType', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='assistance',
            name='FKIdCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course'),
        ),
        migrations.AddField(
            model_name='user',
            name='FKLicenceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserType'),
        ),
    ]
