# Generated by Django 2.1.2 on 2018-12-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Photo'),
        ),
    ]
