# Generated by Django 2.1.2 on 2018-12-17 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181213_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('IdFace', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(blank=True, upload_to='faces/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('IdGroup', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('IdPerson', models.AutoField(primary_key=True, serialize=False)),
                ('FKGroup', models.ForeignKey(on_delete=True, to='users.Group')),
                ('FKLicence', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='face',
            name='FKPerson',
            field=models.ForeignKey(on_delete=True, to='users.Person'),
        ),
    ]
