# Generated by Django 2.1.2 on 2018-12-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181217_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
