# Generated by Django 2.1.2 on 2018-12-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Default',
            field=models.BooleanField(default=False),
        ),
    ]
