# Generated by Django 2.1.2 on 2018-12-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_group_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='IdPersonApi',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
