# Generated by Django 2.1.2 on 2018-12-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_face_persistedfaceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='FKPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='FKGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group'),
        ),
    ]
